### ISSUE TITLE
Allows to save terminal output to ServiceNow instance.

### ISSUE THREAD

**Issue by CGraabaek** [arnoudkooi/sn-scriptsync#30] opened 2019-10-28 08:16 UTC
Sometimes the extension saves my terminal output instead of the widget.

![Screenshot 2019-10-28 at 08 30 31](https://user-images.githubusercontent.com/6660378/67662401-9cd82400-f963-11e9-9e76-7fd824aa0e51.png)

**Comment by arnoudkooi** [comment] 2019-10-28 08:23
do you have some more steps to reproduce? did your html contain css?

**Comment by arnoudkooi** [comment] 2019-11-06 23:06
any more info?

**Comment by CGraabaek** [comment] 2019-11-14 10:55
Yes, if you go to the output section of VS Code, and presses save (ctrl+s || cmd+s) then it will save whatever output is there to the HTML of the widget.

**Comment by Blenderpics** [comment] 2019-11-14 16:52
https://github.com/arnoudkooi/sn-scriptsync/blob/662907d0782e11c53e6c5285f6d607529a0c7c46/src/extension.ts#L105  
https://code.visualstudio.com/api/references/vscode-api#TextDocumentChangeEvent  
  
I could not find any way to differentiate `listener.document` between a save operation in the output section vs. in the document section. `listener.document.fileName` and `listener.document.url` contain the path of the actual file in both cases.  
I did however notice, that in my case `listener.contentChanges.length` is always `0` if you press ctl+s in the output tab.  
If thats the case it could be solved by filtering the save events for `listener.contentChanges.length > 0`

**Comment by arnoudkooi** [comment] 2019-11-14 20:25
Thanks for chiming in @Blenderpics 
This pointed in the right direction, expect it to be fixed in v.1.6.1 please try and respond @CGraabaek !

**Comment by CGraabaek** [comment] 2019-11-15 07:19
My response is above Blenderpics', where I tell how i got the error.

**Comment by arnoudkooi** [comment] 2019-11-15 07:21
Sorry, missed that. is it fixed in 1.6.1?

**Comment by Blenderpics** [comment] 2019-11-18 09:29
I can't reproduce it anymore, seems to be fixed for me.

**Comment by CGraabaek** [comment] 2019-11-18 11:58
Yeah it's fixed now! Thanks!

**Comment by arnoudkooi** [comment] 2019-11-18 12:04
Good, I'll close it :)

**Closed by arnoudkooi** 2019-11-18 12:04 UTC
