### ISSUE TITLE
SN Utils Not Sending Script to VS Code

### ISSUE THREAD

**Issue by V1tamnT** [arnoudkooi/sn-scriptsync#89] opened 2023-08-18 14:02 UTC
Using sn-scriptsync V3.0. I can't get the script to show up in VS Code. Thinking this may have something to do with the new naming, I changed folders to a new structure but still have the same issue. I watched the video but didn't see anything that would help with this issue.

![image](https://github.com/arnoudkooi/sn-scriptsync/assets/20115051/08e87f54-8b4b-46af-b0f8-88e5e829e322)

When I hit the sn-scriptsync button in VS Code, I don't see any of the options displayed in the video.

What might I be doing wrong?

**Comment by arnoudkooi** [comment] 2023-08-18 14:21
Do you have access to the sys_scope table? Maybe easiest to quickly jump on a call?

**Comment by V1tamnT** [comment] 2023-08-18 14:36
Yes, I do have access to sys_scope. I'm an instance admin so I can pretty much access anything, save HR data. As for calls, I don't have a great way to get on one other than potentially Discord.

**Comment by arnoudkooi** [comment] 2023-08-18 18:39
Ping me over there (I did not see your handle there)

**Comment by Sauron-Dev** [comment] 2023-08-21 05:31
I have the same problem. I can pull for example widget files with no problem but the ng_template record wont load. Did you guys find already a fix for that?

**Comment by V1tamnT** [comment] 2023-08-21 14:12
I am away from my computer today, but I did a test earlier today and the script include I tried to edit popped in. I'll need to get back to you to see if it was a client script issue I was having or if it magic'd itself back to working.

So far, everything I've tried is in Global.

**Comment by VanWeapon** [comment] 2023-08-22 00:04
I have similar symptoms, my issue is that the script I want to load is attached to a record in a scope, but that record's table does not extend sys_metadata. Syncing the whole scope does not load these records (understandable) but the manual sync button also doesn't work.

Confirmed this by reproducing on a PDI:
Create a scoped app
Create a table in the app which does not extend any other table 
Add a script field to it
Open vscode and sync scoped app artefacts
Try sync the script field to VS Code 
Doesnt work
Create another table which does extend sys_metadata
Repeat above
Sync works

**Comment by V1tamnT** [comment] 2023-08-22 00:33
In my case, I don't even get the option to sync from sys_scope in VS Code...it's not an option. Not sure what's going on there, but in some basic testing I cannot send sked jobs nor can I send client scripts...of any type...to VS Code. In some instances, the client script seems to be saved as a file, but it will not open automatically.

Really hoping this is something on my side that needs tweaking and not something on the instance I have to fix. That gets a bit sticky with our Tech Sec department.

**Comment by Sauron-Dev** [comment] 2023-08-22 05:52
It seems like @VanWeapon described.

**Comment by arnoudkooi** [comment] 2023-08-22 07:37
I just published version 3.0.7 this version places the file in the folder `no_scope` when the scope can not be determined.
Hope this gives a little relief.
Note that custom script fields will not be included in the "Load scope" sync at this point.

For the other issues described here, please check in with me to arrange a troubleshooting call.

**Comment by Sauron-Dev** [comment] 2023-08-22 10:44
I can confirm that it works now for me, thank you very much for this fast response and bugfix!

**Comment by V1tamnT** [comment] 2023-08-22 11:38
Client scripts and sked jobs load for me now, thanks!

Not sure if it's important or not, but I still can't see a list of scopes for some reason. 

![image](https://github.com/arnoudkooi/sn-scriptsync/assets/20115051/dccca2a2-4c5a-4752-9951-3988469c9902)

I checked the ACLs on sys_scope and they all seem to be OOB and I do have the expected admin permissions for this table. If this is unimportant at this time, then I'm good.

**Comment by arnoudkooi** [comment] 2023-08-22 12:05
I would like to jump on a call with someone who experiences this.
Please ping me.

**Comment by V1tamnT** [comment] 2023-08-22 12:22
I'm unable to do this right now, but I'd be willing to do it, provided we can find the time and a method. What are the times you are available and what methods do you have to chat?

**Comment by V1tamnT** [comment] 2023-08-23 14:13
Hey @arnoudkooi, just wanted to follow up to see if we could connect on this. I'm a daily, all-day user of this and anything I can do to help out, I'm happy to oblige. Just need to find a time and a method to connect.

**Comment by arnoudkooi** [comment] 2023-08-23 14:41
Im available, on most channels. Could check in now! apps@arnoudkooi.com

**Comment by V1tamnT** [comment] 2023-08-23 14:53
I'm free for a bit this afternoon and I could meet with Teams, if you have that available. I could also probably meet on Zoom if that works. My best availability would be between 1:00 PM and 2:00 PM Eastern. If this doesn't work, I'm free for a bit at 10:30 AM Eastern tomorrow and most of the afternoon.

**Comment by arnoudkooi** [comment] 2023-08-23 18:12
Thanks for your time.

in 3.0.9 there should be an update that loads the treeview more consistently after starting the scriptsync.
One tip: 
Fill in the folder name in the **path** setting you use as your workspace, that way sn-scriptsync will auto-start when you open that folder.
![Code20230823 - 2009](https://github.com/arnoudkooi/sn-scriptsync/assets/840781/7ccfa1dd-8afe-45d4-b944-afed2a2b8395)
(this was the reason it didn't show for you)

**Comment by arnoudkooi** [comment] 2023-08-24 10:53
Closing this one. Hope all is good now

**Closed by arnoudkooi** 2023-08-24 10:53 UTC
